### ISSUE TITLE
Weird space at the top of the map page

### ISSUE THREAD

**Issue by maraf** [neptuo/Recollections#192]
![image](https://user-images.githubusercontent.com/10020471/96846725-91261d00-1452-11eb-89f5-b25927d637f4.png)

Probably `site.scss`:

```CSS
.mappage {
    ...
    top: 70px;
    ...
}
```
